import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, test } from "vitest";

import { reconcile, type TaggedChange } from "../src/reconcile.js";
import { emptyLockfile } from "../src/lockfile.js";

let root: string;
const GEN = "agent-setup@test";

beforeEach(async () => {
  root = await fs.mkdtemp(path.join(tmpdir(), "agent-setup-recon-"));
  // make a .agents/skills/foo dir so symlink targets are realistic
  await fs.mkdir(path.join(root, ".agents", "skills", "foo"), {
    recursive: true,
  });
  await fs.writeFile(
    path.join(root, ".agents", "skills", "foo", "SKILL.md"),
    "---\nname: foo\ndescription: x\n---\n# foo\n",
    "utf8",
  );
});

afterEach(async () => {
  await fs.rm(root, { recursive: true, force: true });
});

function neonChange(emitter = "cursor"): TaggedChange {
  return {
    emitter,
    kind: "json-entry",
    path: path.join(root, ".cursor", "mcp.json"),
    pointer: "mcpServers.neon",
    value: { command: "npx", args: ["@neondatabase/mcp-server-neon@latest"] },
    ownerKey: "mcpServers.neon",
  };
}

function fooSymlink(emitter = "claude"): TaggedChange {
  return {
    emitter,
    kind: "symlink",
    link: path.join(root, ".claude", "skills", "foo"),
    target: path.join(root, ".agents", "skills", "foo"),
  };
}

const CLAUDE_MARKER = "# Generated by agent-setup";

function claudeMd(emitter = "claude"): TaggedChange {
  return {
    emitter,
    kind: "text-file",
    path: path.join(root, "CLAUDE.md"),
    content: `${CLAUDE_MARKER}\n@AGENTS.md\n`,
    marker: CLAUDE_MARKER,
  };
}

describe("reconcile — idempotency", () => {
  test("second run produces no writes", async () => {
    const changes: TaggedChange[] = [neonChange(), fooSymlink(), claudeMd()];
    const r1 = await reconcile({
      changes,
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    expect(r1.refusals).toEqual([]);
    // Re-run with same changes and the lockfile from the first run.
    const r2 = await reconcile({
      changes,
      prevLockfile: r1.newLockfile,
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    expect(r2.refusals).toEqual([]);
    // No write/sweep should have made changes.
    for (const a of r2.applied) {
      if (
        a.kind === "json-write" ||
        a.kind === "toml-write" ||
        a.kind === "text-write" ||
        a.kind === "symlink-write"
      ) {
        expect(a.noop).toBe(true);
      } else {
        // sweeps mean "would remove" — must be empty between equal runs.
        throw new Error(`unexpected sweep on idempotent run: ${a.kind}`);
      }
    }
  });
});

describe("reconcile — preservation", () => {
  test("hand-added cursor mcp entry survives", async () => {
    const cursorFile = path.join(root, ".cursor", "mcp.json");
    await fs.mkdir(path.dirname(cursorFile), { recursive: true });
    await fs.writeFile(
      cursorFile,
      JSON.stringify(
        {
          mcpServers: {
            "my-personal": { command: "node", args: ["./hand.js"] },
          },
        },
        null,
        2,
      ) + "\n",
      "utf8",
    );

    await reconcile({
      changes: [neonChange()],
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    const after = JSON.parse(await fs.readFile(cursorFile, "utf8"));
    expect(after.mcpServers["my-personal"]).toEqual({
      command: "node",
      args: ["./hand.js"],
    });
    expect(after.mcpServers.neon).toEqual({
      command: "npx",
      args: ["@neondatabase/mcp-server-neon@latest"],
    });
  });
});

describe("reconcile — marker refusal", () => {
  test("refuses to overwrite hand-written file without marker", async () => {
    const claudeFile = path.join(root, "CLAUDE.md");
    await fs.writeFile(claudeFile, "my own claude file\n", "utf8");
    const r = await reconcile({
      changes: [claudeMd()],
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    expect(r.refusals).toHaveLength(1);
    expect(r.refusals[0]?.kind).toBe("marker-missing");
    expect(r.refusals[0]?.path).toBe(claudeFile);
    const text = await fs.readFile(claudeFile, "utf8");
    expect(text).toBe("my own claude file\n");
  });

  test("force overwrites", async () => {
    const claudeFile = path.join(root, "CLAUDE.md");
    await fs.writeFile(claudeFile, "my own claude file\n", "utf8");
    const r = await reconcile({
      changes: [claudeMd()],
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: true,
      dryRun: false,
    });
    expect(r.refusals).toEqual([]);
    const text = await fs.readFile(claudeFile, "utf8");
    expect(text.startsWith(CLAUDE_MARKER)).toBe(true);
    expect(text).toContain("@AGENTS.md");
  });
});

describe("reconcile — real-dir refusal", () => {
  test("refuses to overwrite real directory at symlink path", async () => {
    const link = path.join(root, ".claude", "skills", "foo");
    await fs.mkdir(link, { recursive: true });
    await fs.writeFile(path.join(link, "real.md"), "real\n", "utf8");
    const r = await reconcile({
      changes: [fooSymlink()],
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    expect(r.refusals).toHaveLength(1);
    expect(r.refusals[0]?.kind).toBe("real-dir-conflict");
    const stat = await fs.lstat(link);
    expect(stat.isDirectory()).toBe(true);
    expect(stat.isSymbolicLink()).toBe(false);
    const real = await fs.readFile(path.join(link, "real.md"), "utf8");
    expect(real).toBe("real\n");
  });
});

describe("reconcile — orphan sweep MCPs", () => {
  test("removes MCP that vanished, preserves hand-added", async () => {
    // Round 1: install neon.
    const r1 = await reconcile({
      changes: [neonChange()],
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    const cursorFile = path.join(root, ".cursor", "mcp.json");
    let doc = JSON.parse(await fs.readFile(cursorFile, "utf8"));
    expect(doc.mcpServers.neon).toBeDefined();

    // User hand-adds another server.
    doc.mcpServers["my-personal"] = { command: "node", args: ["./hand.js"] };
    await fs.writeFile(cursorFile, JSON.stringify(doc, null, 2) + "\n", "utf8");

    // Round 2: no neon in changes.
    const r2 = await reconcile({
      changes: [],
      prevLockfile: r1.newLockfile,
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    expect(r2.refusals).toEqual([]);
    const after = JSON.parse(await fs.readFile(cursorFile, "utf8"));
    expect(after.mcpServers.neon).toBeUndefined();
    expect(after.mcpServers["my-personal"]).toEqual({
      command: "node",
      args: ["./hand.js"],
    });
    expect(r2.newLockfile.owns.mcps["neon"]).toBeUndefined();
  });
});

describe("reconcile — orphan sweep skills", () => {
  test("removes orphan symlink", async () => {
    const r1 = await reconcile({
      changes: [fooSymlink()],
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    const link = path.join(root, ".claude", "skills", "foo");
    expect((await fs.lstat(link)).isSymbolicLink()).toBe(true);

    const r2 = await reconcile({
      changes: [],
      prevLockfile: r1.newLockfile,
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    expect(r2.refusals).toEqual([]);
    let exists = true;
    try {
      await fs.lstat(link);
    } catch {
      exists = false;
    }
    expect(exists).toBe(false);
    expect(r2.newLockfile.owns.skills["foo"]).toBeUndefined();
  });
});

describe("reconcile — dry run", () => {
  test("populates applied but writes nothing", async () => {
    const r = await reconcile({
      changes: [neonChange(), fooSymlink(), claudeMd()],
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: true,
    });
    expect(r.applied.length).toBeGreaterThan(0);
    // None of the target files/links should exist.
    for (const p of [
      path.join(root, ".cursor", "mcp.json"),
      path.join(root, ".claude", "skills", "foo"),
      path.join(root, "CLAUDE.md"),
    ]) {
      let existed = true;
      try {
        await fs.lstat(p);
      } catch {
        existed = false;
      }
      expect(existed).toBe(false);
    }
    // Lockfile is computed but nothing should be written to disk.
    expect(r.newLockfile.owns.mcps["neon"]).toBeDefined();
  });
});

describe("reconcile — Gemini context.fileName as file-level entry", () => {
  test("classifies non-mcp ownerKey as file entry and sweeps it", async () => {
    const settings = path.join(root, ".gemini", "settings.json");
    const change: TaggedChange = {
      emitter: "gemini",
      kind: "json-entry",
      path: settings,
      pointer: "context.fileName",
      value: "AGENTS.md",
      ownerKey: "context.fileName",
    };
    const r1 = await reconcile({
      changes: [change],
      prevLockfile: emptyLockfile(),
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    // Should not appear under owns.mcps.
    expect(r1.newLockfile.owns.mcps).toEqual({});
    // Should appear under owns.files keyed with #
    const fileKey = `${settings}#context.fileName`;
    expect(r1.newLockfile.owns.files[fileKey]).toBeDefined();
    const after = JSON.parse(await fs.readFile(settings, "utf8"));
    expect(after.context.fileName).toBe("AGENTS.md");

    // Sweep: rerun with no changes.
    const r2 = await reconcile({
      changes: [],
      prevLockfile: r1.newLockfile,
      scope: "project",
      root,
      generator: GEN,
      force: false,
      dryRun: false,
    });
    const swept = JSON.parse(await fs.readFile(settings, "utf8"));
    expect(swept.context?.fileName).toBeUndefined();
    expect(r2.refusals).toEqual([]);
  });
});
