// Claude Code emitter.
//
// - Skills: per-skill symlink at .claude/skills/<name> → .agents/skills/<name>
//           (project) or ~/.claude/skills/<name> (global, but symlink target
//           still points at the project's .agents/skills/<name> — that's
//           what the loader produced; for a global source root, the caller
//           passes `root = homedir()` and we emit ~/.claude/skills/<name>
//           → ~/.agents/skills/<name>).
// - MCP:    json-entry at mcpServers.<name> in
//             .mcp.json (project) | ~/.claude.json (global).
// - AGENTS: text-file CLAUDE.md = "@AGENTS.md\n" (project only).

import { homedir } from "node:os";
import path from "node:path";

import { detectClaude } from "../detect.js";
import type { DesiredChange, EmitInput, Emitter } from "../types.js";
import {
  bearerHeaderDollar,
  isHttpTransport,
  isStdioTransport,
} from "./shared.js";
import type { Server } from "../schema.js";

const CLAUDE_MD_MARKER = "# Generated by agent-setup";

function buildEntry(server: Server): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (isStdioTransport(server)) {
    out["command"] = server.command;
    if (server.args) out["args"] = server.args;
    if (server.env) out["env"] = server.env;
  } else if (isHttpTransport(server)) {
    out["url"] = server.url;
    const headers: Record<string, string> = { ...(server.headers ?? {}) };
    const auth = bearerHeaderDollar(server);
    if (auth) Object.assign(headers, auth);
    if (Object.keys(headers).length > 0) out["headers"] = headers;
  }
  return out;
}

function emit(input: EmitInput): DesiredChange[] {
  const changes: DesiredChange[] = [];
  const isProject = input.scope === "project";

  // mcp file path
  const mcpFile = isProject
    ? path.join(input.root, ".mcp.json")
    : path.join(homedir(), ".claude.json");

  for (const server of input.servers) {
    changes.push({
      kind: "json-entry",
      path: mcpFile,
      pointer: `mcpServers.${server.name}`,
      value: buildEntry(server),
      ownerKey: `mcpServers.${server.name}`,
    });
  }

  // skills as symlinks
  const skillsRoot = isProject
    ? path.join(input.root, ".claude", "skills")
    : path.join(homedir(), ".claude", "skills");
  const agentsSkillsRoot = isProject
    ? path.join(input.root, ".agents", "skills")
    : path.join(homedir(), ".agents", "skills");

  for (const skill of input.skills) {
    changes.push({
      kind: "symlink",
      link: path.join(skillsRoot, skill.name),
      target: path.join(agentsSkillsRoot, skill.name),
    });
  }

  // CLAUDE.md import stub at project scope only.
  if (isProject && input.agentsMd !== null) {
    changes.push({
      kind: "text-file",
      path: path.join(input.root, "CLAUDE.md"),
      content: `${CLAUDE_MD_MARKER}\n@AGENTS.md\n`,
      marker: CLAUDE_MD_MARKER,
    });
  }

  return changes;
}

export const claudeEmitter: Emitter = {
  name: "claude",
  detect: detectClaude,
  emit,
};
