// Reconciler: applies tagged DesiredChanges against the filesystem,
// while diffing against the prior lockfile to sweep orphans.
//
// Safety guarantees enforced here (the only place that touches disk
// in this milestone):
//   - text-file writes refuse to overwrite a present file that lacks
//     our marker on its first line, unless `force: true`.
//   - symlink writes refuse to clobber a real file or real directory.
//     Existing symlinks ARE replaced (target is rewritten).
//   - hand-added entries in shared JSON/TOML files survive (we only
//     touch the entry at the declared `pointer`/`ownerKey`).
//   - orphan removals: anything in prevLockfile.owns but not in the
//     newly-computed owns is removed (json/toml entry deleted, symlink
//     unlinked, marker-tagged file deleted).
//   - `dryRun: true` produces the AppliedChange/Refusal report but
//     never touches the filesystem.
//
// Marker convention (documented for emitter authors):
//   - Each `text-file` change carries its own `marker` string. The
//     reconciler uses it verbatim — both for the marker check on
//     existing files and for the lockfile ownership record.
//   - Conventional markers: `# Generated by agent-setup` for shell-
//     style files, `<!-- Generated by agent-setup -->` for HTML/MD
//     so the marker doesn't render as a heading.
//
// MCP vs file ownership inference:
//   For json-entry / toml-entry changes, we classify as either an
//   "mcp" entry (recorded under owns.mcps) or a "file-level" entry
//   (recorded under owns.files keyed by file path).
//
//   Heuristic: an mcp's `ownerKey` is "<container>.<serverName>" with
//   container ∈ {mcpServers, mcp_servers, mcp}. The trailing segment
//   is the canonical server name. Anything else (e.g. Gemini's
//   "context.fileName") is a file-level entry.

import { promises as fs } from "node:fs";
import path from "node:path";

import * as jsonFmt from "./formats/json.js";
import * as tomlFmt from "./formats/toml.js";
import { emptyLockfile, type Lockfile } from "./lockfile.js";
import type { DesiredChange, Scope } from "./types.js";

export type TaggedChange = DesiredChange & { emitter: string };

export type AppliedChange =
  | { kind: "json-write"; path: string; pointer: string; emitter: string; noop: boolean }
  | { kind: "toml-write"; path: string; pointer: string; emitter: string; noop: boolean }
  | { kind: "text-write"; path: string; emitter: string; noop: boolean }
  | { kind: "symlink-write"; link: string; target: string; emitter: string; noop: boolean }
  | { kind: "json-sweep"; path: string; pointer: string; emitter: string }
  | { kind: "toml-sweep"; path: string; pointer: string; emitter: string }
  | { kind: "text-sweep"; path: string; emitter: string }
  | { kind: "symlink-sweep"; link: string; emitter: string };

export type Refusal =
  | { kind: "marker-missing"; path: string; emitter: string }
  | { kind: "real-dir-conflict"; link: string; emitter: string }
  | { kind: "real-file-conflict"; link: string; emitter: string };

export type ReconcileInput = {
  changes: TaggedChange[];
  prevLockfile: Lockfile;
  scope: Scope;
  root: string;
  generator: string;
  force: boolean;
  dryRun: boolean;
};

export type ReconcileResult = {
  newLockfile: Lockfile;
  applied: AppliedChange[];
  refusals: Refusal[];
};

// ── helpers ──────────────────────────────────────────────────────────────────

function deepEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (typeof a !== typeof b) return false;
  if (a === null || b === null) return false;
  if (Array.isArray(a)) {
    if (!Array.isArray(b)) return false;
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) {
      if (!deepEqual(a[i], b[i])) return false;
    }
    return true;
  }
  if (typeof a === "object" && typeof b === "object") {
    const ao = a as Record<string, unknown>;
    const bo = b as Record<string, unknown>;
    const ak = Object.keys(ao);
    const bk = Object.keys(bo);
    if (ak.length !== bk.length) return false;
    for (const k of ak) {
      if (!Object.prototype.hasOwnProperty.call(bo, k)) return false;
      if (!deepEqual(ao[k], bo[k])) return false;
    }
    return true;
  }
  return false;
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.lstat(p);
    return true;
  } catch {
    return false;
  }
}

async function readFileOr(
  p: string,
  fallback: string | null,
): Promise<string | null> {
  try {
    return await fs.readFile(p, "utf8");
  } catch {
    return fallback;
  }
}

async function atomicWrite(filePath: string, body: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const tmp = filePath + ".tmp";
  await fs.writeFile(tmp, body, "utf8");
  await fs.rename(tmp, filePath);
}

// MCP container detection for json/toml-entry classification.
const MCP_CONTAINERS = new Set(["mcpServers", "mcp_servers", "mcp"]);

function classifyEntry(
  ownerKey: string,
): { kind: "mcp"; name: string } | { kind: "file" } {
  const segs = ownerKey.split(/[./]/g).filter((s) => s.length > 0);
  if (segs.length === 2 && MCP_CONTAINERS.has(segs[0] as string)) {
    return { kind: "mcp", name: segs[1] as string };
  }
  return { kind: "file" };
}

// ── reconcile ────────────────────────────────────────────────────────────────

export async function reconcile(
  input: ReconcileInput,
): Promise<ReconcileResult> {
  const applied: AppliedChange[] = [];
  const refusals: Refusal[] = [];
  const newLockfile: Lockfile = {
    version: 1,
    generator: input.generator,
    owns: { skills: {}, mcps: {}, files: {} },
  };

  // For json/toml changes targeting the same file, batch them so we
  // read once, mutate in-memory, and write once.
  type JsonGroup = {
    path: string;
    items: Array<{
      pointer: string;
      value: unknown;
      ownerKey: string;
      emitter: string;
    }>;
  };
  const jsonGroups = new Map<string, JsonGroup>();
  const tomlGroups = new Map<string, JsonGroup>();

  for (const ch of input.changes) {
    if (ch.kind === "json-entry") {
      let g = jsonGroups.get(ch.path);
      if (!g) {
        g = { path: ch.path, items: [] };
        jsonGroups.set(ch.path, g);
      }
      g.items.push({
        pointer: ch.pointer,
        value: ch.value,
        ownerKey: ch.ownerKey,
        emitter: ch.emitter,
      });
    } else if (ch.kind === "toml-entry") {
      let g = tomlGroups.get(ch.path);
      if (!g) {
        g = { path: ch.path, items: [] };
        tomlGroups.set(ch.path, g);
      }
      g.items.push({
        pointer: ch.pointer,
        value: ch.value,
        ownerKey: ch.ownerKey,
        emitter: ch.emitter,
      });
    }
  }

  // Process json groups.
  for (const g of jsonGroups.values()) {
    const existingText = await readFileOr(g.path, null);
    let doc: unknown = {};
    if (existingText !== null && existingText.trim().length > 0) {
      try {
        doc = JSON.parse(existingText);
      } catch {
        doc = {};
      }
    }
    let mutated = false;
    for (const item of g.items) {
      const cur = jsonFmt.getAtPointer(doc, item.pointer);
      const same = deepEqual(cur, item.value);
      if (!same) {
        doc = jsonFmt.setAtPointer(doc, item.pointer, item.value);
        mutated = true;
      }
      applied.push({
        kind: "json-write",
        path: g.path,
        pointer: item.pointer,
        emitter: item.emitter,
        noop: same,
      });
      // Record ownership.
      const cls = classifyEntry(item.ownerKey);
      if (cls.kind === "mcp") {
        const byEmitter = newLockfile.owns.mcps[cls.name] ?? {};
        byEmitter[item.emitter] = { file: g.path, ownerKey: item.ownerKey };
        newLockfile.owns.mcps[cls.name] = byEmitter;
      } else {
        // File-level json entry — track under owns.files keyed by
        // "<path>#<ownerKey>" so multiple entries in the same file
        // can each be tracked independently. We record the marker
        // as the empty string to indicate "managed entry, not a
        // managed-whole-file."
        const key = `${g.path}#${item.ownerKey}`;
        newLockfile.owns.files[key] = { marker: "", emitter: item.emitter };
      }
    }
    if (mutated && !input.dryRun) {
      await atomicWrite(g.path, jsonFmt.stringifyJson(doc));
    }
  }

  // Process toml groups.
  for (const g of tomlGroups.values()) {
    const existingText = await readFileOr(g.path, null);
    let doc: Record<string, unknown> = {};
    if (existingText !== null && existingText.trim().length > 0) {
      try {
        doc = tomlFmt.parseToml(existingText);
      } catch {
        doc = {};
      }
    }
    let mutated = false;
    for (const item of g.items) {
      const cur = tomlFmt.getAtPointer(doc, item.pointer);
      const same = deepEqual(cur, item.value);
      if (!same) {
        doc = tomlFmt.setAtPointer(doc, item.pointer, item.value);
        mutated = true;
      }
      applied.push({
        kind: "toml-write",
        path: g.path,
        pointer: item.pointer,
        emitter: item.emitter,
        noop: same,
      });
      const cls = classifyEntry(item.ownerKey);
      if (cls.kind === "mcp") {
        const byEmitter = newLockfile.owns.mcps[cls.name] ?? {};
        byEmitter[item.emitter] = { file: g.path, ownerKey: item.ownerKey };
        newLockfile.owns.mcps[cls.name] = byEmitter;
      } else {
        const key = `${g.path}#${item.ownerKey}`;
        newLockfile.owns.files[key] = { marker: "", emitter: item.emitter };
      }
    }
    if (mutated && !input.dryRun) {
      await atomicWrite(g.path, tomlFmt.stringifyToml(doc));
    }
  }

  // Process text-file changes.
  for (const ch of input.changes) {
    if (ch.kind !== "text-file") continue;
    const existing = await readFileOr(ch.path, null);
    if (existing === null) {
      // missing → write
      applied.push({
        kind: "text-write",
        path: ch.path,
        emitter: ch.emitter,
        noop: false,
      });
      if (!input.dryRun) await atomicWrite(ch.path, ch.content);
      newLockfile.owns.files[ch.path] = {
        marker: ch.marker,
        emitter: ch.emitter,
      };
      continue;
    }
    // present → check first line for marker.
    const firstLine = existing.split("\n", 1)[0] ?? "";
    const hasMarker = firstLine.includes(ch.marker);
    if (hasMarker || input.force) {
      const same = existing === ch.content;
      applied.push({
        kind: "text-write",
        path: ch.path,
        emitter: ch.emitter,
        noop: same,
      });
      if (!same && !input.dryRun) await atomicWrite(ch.path, ch.content);
      newLockfile.owns.files[ch.path] = {
        marker: ch.marker,
        emitter: ch.emitter,
      };
    } else {
      refusals.push({
        kind: "marker-missing",
        path: ch.path,
        emitter: ch.emitter,
      });
      // Do NOT record ownership — we don't own a file we couldn't write.
    }
  }

  // Process symlink changes.
  for (const ch of input.changes) {
    if (ch.kind !== "symlink") continue;
    const skillName = path.basename(ch.link);
    let existingStat: import("node:fs").Stats | null = null;
    let existingLstat: import("node:fs").Stats | null = null;
    try {
      existingLstat = await fs.lstat(ch.link);
    } catch {
      existingLstat = null;
    }
    if (existingLstat === null) {
      // create
      applied.push({
        kind: "symlink-write",
        link: ch.link,
        target: ch.target,
        emitter: ch.emitter,
        noop: false,
      });
      if (!input.dryRun) {
        await fs.mkdir(path.dirname(ch.link), { recursive: true });
        await fs.symlink(ch.target, ch.link);
      }
      const byEmitter = newLockfile.owns.skills[skillName] ?? {};
      byEmitter[ch.emitter] = { kind: "symlink", path: ch.link };
      newLockfile.owns.skills[skillName] = byEmitter;
      continue;
    }
    if (existingLstat.isSymbolicLink()) {
      let curTarget = "";
      try {
        curTarget = await fs.readlink(ch.link);
      } catch {
        curTarget = "";
      }
      const same = curTarget === ch.target;
      applied.push({
        kind: "symlink-write",
        link: ch.link,
        target: ch.target,
        emitter: ch.emitter,
        noop: same,
      });
      if (!same && !input.dryRun) {
        await fs.unlink(ch.link);
        await fs.symlink(ch.target, ch.link);
      }
      const byEmitter = newLockfile.owns.skills[skillName] ?? {};
      byEmitter[ch.emitter] = { kind: "symlink", path: ch.link };
      newLockfile.owns.skills[skillName] = byEmitter;
      continue;
    }
    // existing real file or real dir → refuse.
    if (existingLstat.isDirectory()) {
      refusals.push({
        kind: "real-dir-conflict",
        link: ch.link,
        emitter: ch.emitter,
      });
    } else {
      refusals.push({
        kind: "real-file-conflict",
        link: ch.link,
        emitter: ch.emitter,
      });
    }
    // Do not record ownership.
    void existingStat;
  }

  // ── orphan sweep ──────────────────────────────────────────────────────────
  // For each ownership record in prev not present in new, remove.

  // MCP sweeps. Need to group deletes by file so we read/mutate/write once.
  type DeleteGroup = { path: string; pointers: Array<{ pointer: string; emitter: string }> };
  const jsonDeletes = new Map<string, DeleteGroup>();
  const tomlDeletes = new Map<string, DeleteGroup>();

  for (const [name, byEmitter] of Object.entries(input.prevLockfile.owns.mcps)) {
    for (const [emitter, prev] of Object.entries(byEmitter)) {
      const stillOwned = newLockfile.owns.mcps[name]?.[emitter];
      if (stillOwned) continue;
      // Decide json vs toml by file extension. Cheaper than re-classifying.
      const isToml = prev.file.endsWith(".toml");
      const map = isToml ? tomlDeletes : jsonDeletes;
      let g = map.get(prev.file);
      if (!g) {
        g = { path: prev.file, pointers: [] };
        map.set(prev.file, g);
      }
      g.pointers.push({ pointer: prev.ownerKey, emitter });
    }
  }

  // Also sweep file-level entries that vanished. owns.files may include
  // both whole-file ownership (marker non-empty) and json/toml entry-level
  // ownership (marker == "" with key "<path>#<ownerKey>").
  for (const [key, prev] of Object.entries(input.prevLockfile.owns.files)) {
    const stillOwned = newLockfile.owns.files[key];
    if (stillOwned) continue;
    if (key.includes("#")) {
      // entry-level: split path#pointer
      const hashIdx = key.indexOf("#");
      const filePath = key.slice(0, hashIdx);
      const pointer = key.slice(hashIdx + 1);
      const isToml = filePath.endsWith(".toml");
      const map = isToml ? tomlDeletes : jsonDeletes;
      let g = map.get(filePath);
      if (!g) {
        g = { path: filePath, pointers: [] };
        map.set(filePath, g);
      }
      g.pointers.push({ pointer, emitter: prev.emitter });
    } else {
      // whole-file ownership — delete file IF it still has our marker.
      const existing = await readFileOr(key, null);
      if (existing === null) {
        applied.push({ kind: "text-sweep", path: key, emitter: prev.emitter });
        continue;
      }
      const firstLine = existing.split("\n", 1)[0] ?? "";
      if (firstLine.includes(prev.marker)) {
        applied.push({ kind: "text-sweep", path: key, emitter: prev.emitter });
        if (!input.dryRun) {
          try {
            await fs.unlink(key);
          } catch {
            // ignore
          }
        }
      }
      // Else: user took ownership — leave it alone.
    }
  }

  // Apply json deletes.
  for (const g of jsonDeletes.values()) {
    const existingText = await readFileOr(g.path, null);
    if (existingText === null) {
      // already gone
      for (const p of g.pointers) {
        applied.push({
          kind: "json-sweep",
          path: g.path,
          pointer: p.pointer,
          emitter: p.emitter,
        });
      }
      continue;
    }
    let doc: unknown;
    try {
      doc = JSON.parse(existingText);
    } catch {
      doc = {};
    }
    let mutated = false;
    for (const p of g.pointers) {
      const before = jsonFmt.getAtPointer(doc, p.pointer);
      if (before !== undefined) {
        doc = jsonFmt.deleteAtPointer(doc, p.pointer);
        mutated = true;
      }
      applied.push({
        kind: "json-sweep",
        path: g.path,
        pointer: p.pointer,
        emitter: p.emitter,
      });
    }
    if (mutated && !input.dryRun) {
      await atomicWrite(g.path, jsonFmt.stringifyJson(doc));
    }
  }

  // Apply toml deletes.
  for (const g of tomlDeletes.values()) {
    const existingText = await readFileOr(g.path, null);
    if (existingText === null) {
      for (const p of g.pointers) {
        applied.push({
          kind: "toml-sweep",
          path: g.path,
          pointer: p.pointer,
          emitter: p.emitter,
        });
      }
      continue;
    }
    let doc: Record<string, unknown>;
    try {
      doc = tomlFmt.parseToml(existingText);
    } catch {
      doc = {};
    }
    let mutated = false;
    for (const p of g.pointers) {
      const before = tomlFmt.getAtPointer(doc, p.pointer);
      if (before !== undefined) {
        const next = tomlFmt.deleteAtPointer(doc, p.pointer);
        if (next && typeof next === "object" && !Array.isArray(next)) {
          doc = next as Record<string, unknown>;
        }
        mutated = true;
      }
      applied.push({
        kind: "toml-sweep",
        path: g.path,
        pointer: p.pointer,
        emitter: p.emitter,
      });
    }
    if (mutated && !input.dryRun) {
      await atomicWrite(g.path, tomlFmt.stringifyToml(doc));
    }
  }

  // Skill orphan sweep.
  for (const [name, byEmitter] of Object.entries(input.prevLockfile.owns.skills)) {
    for (const [emitter, prev] of Object.entries(byEmitter)) {
      const stillOwned = newLockfile.owns.skills[name]?.[emitter];
      if (stillOwned) continue;
      // Only unlink if it's still a symlink (we don't blow away whatever
      // the user replaced it with).
      let st: import("node:fs").Stats | null = null;
      try {
        st = await fs.lstat(prev.path);
      } catch {
        st = null;
      }
      if (st && st.isSymbolicLink()) {
        applied.push({
          kind: "symlink-sweep",
          link: prev.path,
          emitter,
        });
        if (!input.dryRun) {
          try {
            await fs.unlink(prev.path);
          } catch {
            // ignore
          }
        }
      } else {
        // Stale lockfile entry; user replaced or removed. Still record
        // the sweep in the report so callers know we considered it.
        applied.push({
          kind: "symlink-sweep",
          link: prev.path,
          emitter,
        });
      }
    }
  }

  void emptyLockfile; // keep import for re-export users; intentionally referenced.

  return { newLockfile, applied, refusals };
}
